<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductColor;
use App\Models\ProductDetail;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $cats = Category::pluck('id', 'slug');
        $q   = '?w=800&q=80&fit=crop';
        $b   = 'https://images.unsplash.com/photo-';

        $products = [
            // ── WALLETS ─────────────────────────────────────────────────────
            [
                'category_slug' => 'wallets',
                'name'        => 'The Heritage Bifold',
                'name_ar'     => 'المحفظة التراثية',
                'slug'        => 'heritage-bifold',
                'tagline'     => 'Classic meets refined minimalism.',
                'tagline_ar'  => 'الكلاسيكية تلتقي بالأناقة المصقولة.',
                'description' => 'Our most beloved piece. Crafted from a single hide of full-grain vegetable-tanned leather, chosen for its natural grain and aged character. Every stitch is placed by hand using waxed linen thread that grows stronger with time.',
                'description_ar' => 'قطعتنا الأكثر حبًا. مصنوعة من جلد بقري كامل الحبوب مدبوغ نباتيًا، يتشقق جلدها بأناقة مع مرور الوقت.',
                'material'    => 'Full Grain Vegetable Tanned',
                'material_ar' => 'جلد كامل الحبوب مدبوغ نباتيًا',
                'origin'      => 'Hand-stitched in Muscat, Oman',
                'origin_ar'   => 'مخيط يدويًا في مسقط، عُمان',
                'care'        => 'Condition with a quality leather balm every 6 months. Keep away from prolonged sunlight and moisture.',
                'care_ar'     => 'استخدم بلسم الجلد كل 6 أشهر. ابعده عن أشعة الشمس المباشرة والرطوبة.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days. Gift-wrapped in our signature black box.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل. في صندوقنا الأسود المميز.',
                'price'       => 45.000,
                'badge'       => 'bestseller',
                'is_featured' => true,
                'sort_order'  => 1,
                'images'      => [
                    ['url' => $b.'1627123424574-724758594e93'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1614260938313-a7fc1a7ad0d2'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1601592996763-f05c9c80a7f1'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1628483211662-9bcc692c46dc'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Cognac',     'name_ar' => 'كونياك',     'hex' => '#8B4513', 'sort_order' => 1],
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن',   'hex' => '#3D1C08', 'sort_order' => 2],
                    ['name' => 'Black',      'name_ar' => 'أسود',       'hex' => '#1A1A1A', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => 'Hand-stitched with waxed linen thread',        'detail_ar' => 'مخيط يدويًا بخيط كتان مشمع',         'sort_order' => 1],
                    ['detail' => '8 card slots + 2 bill compartments',           'detail_ar' => '8 فتحات بطاقات + خانتان للأوراق النقدية', 'sort_order' => 2],
                    ['detail' => 'Full grain cowhide, 2 mm thickness',           'detail_ar' => 'جلد بقري كامل الحبوب، سماكة 2 ملم',   'sort_order' => 3],
                    ['detail' => 'Dimensions: 11 cm × 9 cm × 1.5 cm',           'detail_ar' => 'الأبعاد: 11 × 9 × 1.5 سم',             'sort_order' => 4],
                    ['detail' => 'Ages beautifully — develops a rich patina',    'detail_ar' => 'يتحسن مع الوقت ويكتسب بريقًا جميلاً', 'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'wallets',
                'name'        => 'Cardslim Pro',
                'name_ar'     => 'كارد سليم برو',
                'slug'        => 'cardslim-pro',
                'tagline'     => 'Carry less. Look more.',
                'tagline_ar'  => 'احمل أقل. ابدُ أفضل.',
                'description' => 'Engineered for the modern minimalist. Holds up to 6 cards with a smooth thumb-slot for effortless access. Vegetable-tanned calfskin with a burnished edge finish.',
                'description_ar' => 'مصمم للحداثة والبساطة. يحمل حتى 6 بطاقات مع فتحة إبهام سلسة.',
                'material'    => 'Full Grain Calfskin',
                'material_ar' => 'جلد عجل كامل الحبوب',
                'origin'      => 'Hand-stitched in Muscat, Oman',
                'origin_ar'   => 'مخيط يدويًا في مسقط، عُمان',
                'care'        => 'Wipe clean with a dry soft cloth. Apply leather conditioner monthly.',
                'care_ar'     => 'امسح بقطعة قماش ناعمة جافة. استخدم مرطب الجلد شهريًا.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 28.000,
                'badge'       => 'new',
                'is_featured' => true,
                'sort_order'  => 2,
                'images' => [
                    ['url' => $b.'1620109176813-e91290f6c795'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1512358958014-b651a7ee1773'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1579014134953-1580d7f123f3'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1637169797848-12431f1d355c'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 1],
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 2],
                    ['name' => 'Cognac',     'name_ar' => 'كونياك',   'hex' => '#8B4513', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => '6 card slots with thumb-access slot',  'detail_ar' => '6 فتحات بطاقات مع فتحة إبهام',   'sort_order' => 1],
                    ['detail' => 'Vegetable-tanned Italian calfskin',    'detail_ar' => 'جلد عجل إيطالي مدبوغ نباتيًا',   'sort_order' => 2],
                    ['detail' => 'Burnished and painted edges',          'detail_ar' => 'حواف مصقولة ومطلية',              'sort_order' => 3],
                    ['detail' => 'Dimensions: 10 cm × 7 cm × 0.7 cm',  'detail_ar' => 'الأبعاد: 10 × 7 × 0.7 سم',        'sort_order' => 4],
                    ['detail' => 'Slim profile — fits any pocket',       'detail_ar' => 'نحيف ويناسب أي جيب',             'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'wallets',
                'name'        => 'The Passport Folio',
                'name_ar'     => 'حافظة جواز السفر',
                'slug'        => 'passport-folio',
                'tagline'     => 'Travel in absolute style.',
                'tagline_ar'  => 'سافر بأناقة مطلقة.',
                'description' => 'A travel companion worthy of first class. Holds your passport, boarding cards, and up to 8 cards. Lined with hand-painted suede interior.',
                'description_ar' => 'رفيق السفر الفاخر. يحمل جواز سفرك وبطاقات الصعود وما يصل إلى 8 بطاقات.',
                'material'    => 'Full Grain with Suede Interior',
                'material_ar' => 'جلد كامل الحبوب مع بطانة سويدية',
                'origin'      => 'Hand-stitched in Muscat, Oman',
                'origin_ar'   => 'مخيط يدويًا في مسقط، عُمان',
                'care'        => 'Spot clean exterior with a dry cloth. Avoid folding the interior suede.',
                'care_ar'     => 'نظف الخارج بقطعة قماش جافة. تجنب طي البطانة السويدية.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 65.000,
                'badge'       => null,
                'is_featured' => false,
                'sort_order'  => 3,
                'images' => [
                    ['url' => $b.'1614330316567-11d8e572db16'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1624538000860-24716b9050f2'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1646766509831-bb330d97648d'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1637868796504-32f45a96d5a0'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Burgundy', 'name_ar' => 'عنابي',    'hex' => '#6B1A2A', 'sort_order' => 1],
                    ['name' => 'Cognac',   'name_ar' => 'كونياك',   'hex' => '#8B4513', 'sort_order' => 2],
                    ['name' => 'Black',    'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => 'Passport slot + boarding card pocket',  'detail_ar' => 'فتحة جواز سفر + جيب لبطاقة الصعود', 'sort_order' => 1],
                    ['detail' => '8 card slots + SIM card pocket',        'detail_ar' => '8 فتحات بطاقات + جيب شريحة SIM',    'sort_order' => 2],
                    ['detail' => 'Hand-painted suede interior lining',    'detail_ar' => 'بطانة سويدية مطلية يدويًا',          'sort_order' => 3],
                    ['detail' => 'Dimensions: 14.5 cm × 10.5 cm × 1.2 cm', 'detail_ar' => 'الأبعاد: 14.5 × 10.5 × 1.2 سم', 'sort_order' => 4],
                    ['detail' => 'RFID blocking inner layer',             'detail_ar' => 'طبقة داخلية لحجب RFID',             'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'wallets',
                'name'        => 'Zip-Around Wallet',
                'name_ar'     => 'محفظة زيب أراوند',
                'slug'        => 'zip-around-wallet',
                'tagline'     => 'Security and elegance, unified.',
                'tagline_ar'  => 'الأمان والأناقة في قطعة واحدة.',
                'description' => 'The Zip-Around features a full-perimeter brass zip closure. Holds coins, cards and notes without compromise.',
                'description_ar' => 'تتميز بسحاب نحاسي كامل المحيط. تحمل العملات المعدنية والبطاقات والأوراق النقدية.',
                'material'    => 'Full Grain Pebbled Leather',
                'material_ar' => 'جلد كامل الحبوب منقوش',
                'origin'      => 'Hand-stitched in Muscat, Oman',
                'origin_ar'   => 'مخيط يدويًا في مسقط، عُمان',
                'care'        => 'Clean with a leather conditioner cloth. Polish the brass zip periodically.',
                'care_ar'     => 'نظف بقطعة قماش مرطبة للجلد. لمع السحاب النحاسي دوريًا.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 58.000,
                'badge'       => null,
                'is_featured' => false,
                'sort_order'  => 4,
                'images' => [
                    ['url' => $b.'1614330315526-166f2d71e544'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1612023395494-1c4050b68647'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1560472355-536de3962603'.$q,    'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1614260938313-a7fc1a7ad0d2'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 1],
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 2],
                    ['name' => 'Tan',        'name_ar' => 'بيج',      'hex' => '#C4A882', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => 'Full-perimeter solid brass zip',          'detail_ar' => 'سحاب نحاسي صلب كامل المحيط',         'sort_order' => 1],
                    ['detail' => '12 card slots + coin pocket + 2 bill sections', 'detail_ar' => '12 فتحة + جيب عملات + خانتان للأوراق', 'sort_order' => 2],
                    ['detail' => 'Pebbled full grain cowhide',              'detail_ar' => 'جلد بقري كامل الحبوب منقوش',          'sort_order' => 3],
                    ['detail' => 'Dimensions: 19 cm × 9.5 cm × 2 cm',     'detail_ar' => 'الأبعاد: 19 × 9.5 × 2 سم',            'sort_order' => 4],
                    ['detail' => 'Wrist strap loop included',               'detail_ar' => 'حلقة حزام معصم مضمنة',               'sort_order' => 5],
                ],
            ],

            // ── BAGS ────────────────────────────────────────────────────────
            [
                'category_slug' => 'bags',
                'name'        => 'Executive Tote',
                'name_ar'     => 'حقيبة توت التنفيذية',
                'slug'        => 'executive-tote',
                'tagline'     => 'The boardroom deserves better.',
                'tagline_ar'  => 'قاعة الاجتماعات تستحق الأفضل.',
                'description' => 'Commanding and refined. Built for those who move between meetings without losing an ounce of elegance. Full-grain cowhide with brass hardware.',
                'description_ar' => 'فارهة ومهيبة. مصممة لمن يتنقل بين الاجتماعات دون أن يفقد لمحة من الأناقة.',
                'material'    => 'Full Grain Cowhide + Brass Hardware',
                'material_ar' => 'جلد بقري كامل الحبوب + تجهيزات نحاسية',
                'origin'      => 'Hand-crafted in Muscat, Oman',
                'origin_ar'   => 'مصنوعة يدويًا في مسقط، عُمان',
                'care'        => 'Condition with leather balm every 3 months. Store stuffed with paper to maintain shape.',
                'care_ar'     => 'استخدم بلسم الجلد كل 3 أشهر. احفظها محشوة بالورق للحفاظ على شكلها.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 5–7 business days. Delivered in a branded dust bag.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 5-7 أيام عمل. مع كيس حماية مميز.',
                'price'       => 185.000,
                'badge'       => 'bestseller',
                'is_featured' => true,
                'sort_order'  => 5,
                'images' => [
                    ['url' => $b.'1598532163257-ae3c6b2524b6'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1600857062241-98e5dba7f214'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1605733513597-a8f8341084e6'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1622560480654-d96214fdc887'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 1],
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 2],
                    ['name' => 'Cognac',     'name_ar' => 'كونياك',   'hex' => '#8B4513', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => 'Structured full grain cowhide exterior',    'detail_ar' => 'هيكل خارجي من الجلد البقري الكامل', 'sort_order' => 1],
                    ['detail' => 'Suede lined interior with laptop sleeve (up to 15")', 'detail_ar' => 'بطانة سويدية مع جيب لابتوب حتى 15 بوصة', 'sort_order' => 2],
                    ['detail' => 'Solid brass rivets and D-rings',           'detail_ar' => 'برشام نحاسي صلب وحلقات D',           'sort_order' => 3],
                    ['detail' => 'Dimensions: 42 cm × 32 cm × 12 cm',       'detail_ar' => 'الأبعاد: 42 × 32 × 12 سم',           'sort_order' => 4],
                    ['detail' => 'Reinforced leather base studs',            'detail_ar' => 'مسامير قاعدية جلدية معززة',          'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'bags',
                'name'        => 'The Weekender Duffel',
                'name_ar'     => 'حقيبة ويكيندر دافل',
                'slug'        => 'weekender-duffel',
                'tagline'     => 'Your weekend, elevated.',
                'tagline_ar'  => 'عطلتك ترتقي.',
                'description' => 'A timeless travel duffel in heavy full-grain leather. Designed for two to three days away with enough room and structure.',
                'description_ar' => 'حقيبة سفر خالدة من الجلد الثقيل الكامل الحبوب. مصممة لرحلات يومين أو ثلاثة.',
                'material'    => 'Heavy Full Grain Cowhide',
                'material_ar' => 'جلد بقري كامل الحبوب ثقيل',
                'origin'      => 'Hand-crafted in Muscat, Oman',
                'origin_ar'   => 'مصنوعة يدويًا في مسقط، عُمان',
                'care'        => 'Apply mink oil before first use. Condition bi-annually. Store in dust bag.',
                'care_ar'     => 'ضع زيت المنك قبل الاستخدام الأول. رطب مرتين سنويًا. احفظ في كيس الحماية.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 7–10 business days. Delivered in a branded dust bag.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 7-10 أيام عمل.',
                'price'       => 245.000,
                'badge'       => null,
                'is_featured' => false,
                'sort_order'  => 6,
                'images' => [
                    ['url' => $b.'1705909237050-7a7625b47fac'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1473188588951-666fce8e7c68'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1613482184972-f9c1022d0928'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1523779105320-d1cd346ff52b'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Cognac',     'name_ar' => 'كونياك',   'hex' => '#8B4513', 'sort_order' => 1],
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 2],
                ],
                'details' => [
                    ['detail' => 'Heavy-duty full grain exterior (3 mm hide)', 'detail_ar' => 'خارج ثقيل كامل الحبوب (3 ملم)',    'sort_order' => 1],
                    ['detail' => 'YKK brass zip closure',                       'detail_ar' => 'سحاب YKK نحاسي',                  'sort_order' => 2],
                    ['detail' => 'Interior: main compartment + 2 zip pockets + shoe bag', 'detail_ar' => 'الداخل: حجرة رئيسية + 2 جيب + حقيبة أحذية', 'sort_order' => 3],
                    ['detail' => 'Dimensions: 55 cm × 30 cm × 28 cm',          'detail_ar' => 'الأبعاد: 55 × 30 × 28 سم',        'sort_order' => 4],
                    ['detail' => 'Detachable shoulder strap + carry handles',   'detail_ar' => 'حزام كتف قابل للفصل + مقابض',    'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'bags',
                'name'        => 'Slim Messenger',
                'name_ar'     => 'حقيبة سليم ميسنجر',
                'slug'        => 'slim-messenger',
                'tagline'     => 'Cross-body confidence.',
                'tagline_ar'  => 'ثقة على الكتف.',
                'description' => 'Light enough to forget, refined enough to remember. Keeps your essentials perfectly ordered with a slim profile.',
                'description_ar' => 'خفيفة بما يكفي لتنساها، أنيقة بما يكفي لتتذكرها.',
                'material'    => 'Full Grain Pebbled Cowhide',
                'material_ar' => 'جلد بقري كامل الحبوب منقوش',
                'origin'      => 'Hand-crafted in Muscat, Oman',
                'origin_ar'   => 'مصنوعة يدويًا في مسقط، عُمان',
                'care'        => 'Condition regularly. The pebbled texture naturally resists minor scratches.',
                'care_ar'     => 'رطب بانتظام. النقش الطبيعي يقاوم الخدوش البسيطة.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 5–7 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 5-7 أيام عمل.',
                'price'       => 138.000,
                'badge'       => 'new',
                'is_featured' => false,
                'sort_order'  => 7,
                'images' => [
                    ['url' => $b.'1575032617751-6ddec2089882'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1624687943971-e86af76d57de'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1622560257067-108402fcedc0'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1622560480605-d83c853bc5c3'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 1],
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 2],
                    ['name' => 'Tan',        'name_ar' => 'بيج',      'hex' => '#C4A882', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => 'Main compartment with zip closure',        'detail_ar' => 'حجرة رئيسية بسحاب',                'sort_order' => 1],
                    ['detail' => 'Front flap pocket with magnetic snap',     'detail_ar' => 'جيب أمامي بمغناطيس',              'sort_order' => 2],
                    ['detail' => 'Adjustable leather shoulder strap',        'detail_ar' => 'حزام كتف جلدي قابل للتعديل',     'sort_order' => 3],
                    ['detail' => 'Dimensions: 34 cm × 26 cm × 8 cm',       'detail_ar' => 'الأبعاد: 34 × 26 × 8 سم',         'sort_order' => 4],
                    ['detail' => 'Brass buckle and D-ring hardware',         'detail_ar' => 'إبزيم نحاسي وحلقات D',            'sort_order' => 5],
                ],
            ],

            // ── BELTS ───────────────────────────────────────────────────────
            [
                'category_slug' => 'belts',
                'name'        => 'Classic Belt No. 1',
                'name_ar'     => 'الحزام الكلاسيكي رقم 1',
                'slug'        => 'classic-belt-no-1',
                'tagline'     => 'The one belt every wardrobe needs.',
                'tagline_ar'  => 'الحزام الذي يحتاجه كل خزانة.',
                'description' => 'Clean lines, solid brass, perfect width. Cut from a single strip of full-grain leather with a hand-bevelled and burnished edge.',
                'description_ar' => 'خطوط نظيفة، نحاس صلب، عرض مثالي. مقطوع من شريط واحد من الجلد الكامل الحبوب.',
                'material'    => 'Full Grain Vegetable Tanned',
                'material_ar' => 'جلد كامل الحبوب مدبوغ نباتيًا',
                'origin'      => 'Hand-cut in Muscat, Oman',
                'origin_ar'   => 'مقطوع يدويًا في مسقط، عُمان',
                'care'        => 'Wipe with a dry cloth after use. Condition annually. Store rolled, not folded.',
                'care_ar'     => 'امسح بقطعة قماش جافة. رطب سنويًا. احفظ ملفوفًا لا مطويًا.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 38.000,
                'badge'       => 'bestseller',
                'is_featured' => true,
                'sort_order'  => 8,
                'images' => [
                    ['url' => $b.'1664286074176-5206ee5dc878'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1664285612706-b32633c95820'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1711443982852-b3df5c563448'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1666723043169-22e29545675c'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 1],
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 2],
                    ['name' => 'Cognac',     'name_ar' => 'كونياك',   'hex' => '#8B4513', 'sort_order' => 3],
                    ['name' => 'Tan',        'name_ar' => 'بيج',      'hex' => '#C4A882', 'sort_order' => 4],
                ],
                'details' => [
                    ['detail' => 'Single piece full grain leather',          'detail_ar' => 'قطعة واحدة من الجلد الكامل الحبوب', 'sort_order' => 1],
                    ['detail' => 'Solid brass roller buckle',                'detail_ar' => 'إبزيم بكرة نحاسي صلب',              'sort_order' => 2],
                    ['detail' => 'Hand-bevelled and burnished edges',        'detail_ar' => 'حواف مشطوفة ومصقولة يدويًا',        'sort_order' => 3],
                    ['detail' => 'Width: 3.5 cm | Lengths: 90–120 cm',      'detail_ar' => 'العرض: 3.5 سم | الأطوال: 90-120 سم','sort_order' => 4],
                    ['detail' => 'Lifetime buckle warranty',                 'detail_ar' => 'ضمان مدى الحياة على الإبزيم',       'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'belts',
                'name'        => 'The Dress Belt',
                'name_ar'     => 'حزام درس بيلت',
                'slug'        => 'dress-belt',
                'tagline'     => 'Formal occasions deserve this.',
                'tagline_ar'  => 'المناسبات الرسمية تستحق هذا.',
                'description' => 'For suits, thobes, and every occasion where details matter. Cut 3 cm wide from a hair-thin full-grain hide with a gold-tone buckle.',
                'description_ar' => 'للبدل والدشاديش وكل مناسبة تهم فيها التفاصيل. عرض 3 سم من جلد رفيع كامل الحبوب.',
                'material'    => 'Slim Full Grain Calfskin',
                'material_ar' => 'جلد عجل رفيع كامل الحبوب',
                'origin'      => 'Hand-cut in Muscat, Oman',
                'origin_ar'   => 'مقطوع يدويًا في مسقط، عُمان',
                'care'        => 'Store flat in a dry place. Clean with a barely damp cloth. Polish with colorless cream.',
                'care_ar'     => 'احفظ مسطحًا في مكان جاف. نظف بقطعة قماش مبللة قليلاً.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 48.000,
                'badge'       => null,
                'is_featured' => false,
                'sort_order'  => 9,
                'images' => [
                    ['url' => $b.'1664286022075-8e997e95bd17'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1624222247344-550fb60583dc'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1705493655920-20c572928501'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1631160246898-58192f971b5f'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 1],
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 2],
                ],
                'details' => [
                    ['detail' => 'Slim calfskin cut — 3 cm wide',            'detail_ar' => 'جلد عجل رفيع بعرض 3 سم',           'sort_order' => 1],
                    ['detail' => 'Hand-polished gold-tone pin buckle',        'detail_ar' => 'إبزيم ذهبي اللون مصقول يدويًا',    'sort_order' => 2],
                    ['detail' => 'Mirror-finished leather back surface',      'detail_ar' => 'سطح خلفي من الجلد بتشطيب مرآة',   'sort_order' => 3],
                    ['detail' => 'Width: 3 cm | Lengths: 85–115 cm',         'detail_ar' => 'العرض: 3 سم | الأطوال: 85-115 سم', 'sort_order' => 4],
                    ['detail' => 'Ideal for formal wear',                     'detail_ar' => 'مثالي للملابس الرسمية',            'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'belts',
                'name'        => 'Reversible Belt',
                'name_ar'     => 'الحزام القابل للعكس',
                'slug'        => 'reversible-belt',
                'tagline'     => 'Two belts. One buckle.',
                'tagline_ar'  => 'حزامان. إبزيم واحد.',
                'description' => 'The Reversible Belt gives you two premium leather surfaces — rotate the buckle 180° to switch from dark brown to black in seconds.',
                'description_ar' => 'حزامان فاخران بإبزيم واحد. أدر الإبزيم 180 درجة للتبديل بين البني الداكن والأسود.',
                'material'    => 'Double-Sided Full Grain Leather',
                'material_ar' => 'جلد كامل الحبوب ثنائي الوجه',
                'origin'      => 'Hand-crafted in Muscat, Oman',
                'origin_ar'   => 'مصنوع يدويًا في مسقط، عُمان',
                'care'        => 'Condition both sides annually. Store with the buckle unclasped.',
                'care_ar'     => 'رطب كلا الوجهين سنويًا. احفظ مع الإبزيم مفتوحًا.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 55.000,
                'badge'       => 'new',
                'is_featured' => false,
                'sort_order'  => 10,
                'images' => [
                    ['url' => $b.'1664286022007-9d2eb1003165'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1664286074240-d7059e004dff'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1554825959-e9a6670d4f18'.$q,    'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1679759022456-a7eae2257ba2'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Brown/Black Reversible', 'name_ar' => 'بني/أسود قابل للعكس', 'hex' => '#2D1B0E', 'sort_order' => 1],
                ],
                'details' => [
                    ['detail' => 'Both surfaces: genuine full grain leather',  'detail_ar' => 'كلا السطحين: جلد حقيقي كامل الحبوب', 'sort_order' => 1],
                    ['detail' => 'Rotating solid brass buckle mechanism',      'detail_ar' => 'آلية إبزيم نحاسي صلب دوارة',        'sort_order' => 2],
                    ['detail' => 'No seams visible on either side',            'detail_ar' => 'لا خياطة ظاهرة على أي وجه',         'sort_order' => 3],
                    ['detail' => 'Width: 3.5 cm | Lengths: 90–120 cm',        'detail_ar' => 'العرض: 3.5 سم | الأطوال: 90-120 سم','sort_order' => 4],
                    ['detail' => 'Two belts in one — exceptional value',       'detail_ar' => 'حزامان بسعر واحد — قيمة استثنائية', 'sort_order' => 5],
                ],
            ],

            // ── ACCESSORIES ─────────────────────────────────────────────────
            [
                'category_slug' => 'accessories',
                'name'        => 'Heritage Key Fob',
                'name_ar'     => 'مفتاح فوب التراثي',
                'slug'        => 'heritage-key-fob',
                'tagline'     => 'Small but unmistakable.',
                'tagline_ar'  => 'صغير لكنه لا يُنسى.',
                'description' => 'A key fob that makes every entrance a statement. Full-grain leather wrap with a polished brass D-ring and the Artisan Leather embossed logo.',
                'description_ar' => 'حلية مفاتيح تجعل كل دخول جملة. ملفوف بجلد كامل الحبوب مع حلقة D نحاسية مصقولة.',
                'material'    => 'Full Grain Leather + Brass',
                'material_ar' => 'جلد كامل الحبوب + نحاس',
                'origin'      => 'Hand-made in Muscat, Oman',
                'origin_ar'   => 'مصنوع يدويًا في مسقط، عُمان',
                'care'        => 'Apply a small amount of leather conditioner to keep supple. Wipe brass with a dry cloth.',
                'care_ar'     => 'ضع كمية صغيرة من مرطب الجلد. امسح النحاس بقطعة قماش جافة.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 18.000,
                'badge'       => null,
                'is_featured' => false,
                'sort_order'  => 11,
                'images' => [
                    ['url' => $b.'1611937685025-8d1df67a80b6'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1549654929-e63d34779e41'.$q,    'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1665573708655-7320ed78bbeb'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1664286074176-5206ee5dc878'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Cognac',     'name_ar' => 'كونياك',   'hex' => '#8B4513', 'sort_order' => 1],
                    ['name' => 'Dark Brown', 'name_ar' => 'بني داكن', 'hex' => '#3D1C08', 'sort_order' => 2],
                    ['name' => 'Black',      'name_ar' => 'أسود',     'hex' => '#1A1A1A', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => 'Full grain leather wrap',                   'detail_ar' => 'غلاف من الجلد الكامل الحبوب',     'sort_order' => 1],
                    ['detail' => 'Polished solid brass D-ring',               'detail_ar' => 'حلقة D نحاسية صلبة مصقولة',       'sort_order' => 2],
                    ['detail' => 'Artisan Leather debossed logo',             'detail_ar' => 'شعار آرتيزان ليذر منقوش',          'sort_order' => 3],
                    ['detail' => 'Length: 12 cm | Width: 2.5 cm',            'detail_ar' => 'الطول: 12 سم | العرض: 2.5 سم',    'sort_order' => 4],
                    ['detail' => 'Fits standard key rings',                   'detail_ar' => 'يناسب حلقات المفاتيح القياسية',   'sort_order' => 5],
                ],
            ],
            [
                'category_slug' => 'accessories',
                'name'        => 'Slim Card Case',
                'name_ar'     => 'حافظة بطاقات سليم',
                'slug'        => 'slim-card-case',
                'tagline'     => 'A pocket statement.',
                'tagline_ar'  => 'بيان في الجيب.',
                'description' => 'The Slim Card Case holds 4 cards with a polished, rigid structure that slips in and out of any pocket effortlessly. Monogramming available.',
                'description_ar' => 'تحمل 4 بطاقات بهيكل صلب أنيق. نقش الأحرف الأولى متاح عند الطلب.',
                'material'    => 'Full Grain Calfskin',
                'material_ar' => 'جلد عجل كامل الحبوب',
                'origin'      => 'Hand-made in Muscat, Oman',
                'origin_ar'   => 'مصنوعة يدويًا في مسقط، عُمان',
                'care'        => 'Wipe with a dry cloth. Avoid bending. Condition lightly once a season.',
                'care_ar'     => 'امسح بقطعة قماش جافة. تجنب الثني. رطب خفيفًا مرة كل موسم.',
                'shipping'    => 'Complimentary delivery across Oman & GCC. 3–5 business days.',
                'shipping_ar' => 'توصيل مجاني في عُمان ودول الخليج. 3-5 أيام عمل.',
                'price'       => 22.000,
                'badge'       => 'new',
                'is_featured' => false,
                'sort_order'  => 12,
                'images' => [
                    ['url' => $b.'1627123424574-724758594e93'.$q, 'label' => 'Front',  'sort_order' => 1],
                    ['url' => $b.'1601592996763-f05c9c80a7f1'.$q, 'label' => 'Side',   'sort_order' => 2],
                    ['url' => $b.'1512358958014-b651a7ee1773'.$q, 'label' => 'Open',   'sort_order' => 3],
                    ['url' => $b.'1614260938313-a7fc1a7ad0d2'.$q, 'label' => 'Detail', 'sort_order' => 4],
                ],
                'colors' => [
                    ['name' => 'Black',    'name_ar' => 'أسود',   'hex' => '#1A1A1A', 'sort_order' => 1],
                    ['name' => 'Cognac',   'name_ar' => 'كونياك', 'hex' => '#8B4513', 'sort_order' => 2],
                    ['name' => 'Burgundy', 'name_ar' => 'عنابي',  'hex' => '#6B1A2A', 'sort_order' => 3],
                ],
                'details' => [
                    ['detail' => '4 card slots',                               'detail_ar' => '4 فتحات بطاقات',                  'sort_order' => 1],
                    ['detail' => 'Rigid structure — cards stay neat',          'detail_ar' => 'هيكل صلب — البطاقات تبقى منظمة', 'sort_order' => 2],
                    ['detail' => 'Monogramming available on request',          'detail_ar' => 'نقش الأحرف الأولى بالطلب',       'sort_order' => 3],
                    ['detail' => 'Dimensions: 9.5 cm × 6.5 cm × 0.6 cm',     'detail_ar' => 'الأبعاد: 9.5 × 6.5 × 0.6 سم',   'sort_order' => 4],
                    ['detail' => 'Perfect as a gift',                          'detail_ar' => 'مثالية كهدية',                    'sort_order' => 5],
                ],
            ],
        ];

        foreach ($products as $data) {
            $catId   = $cats[$data['category_slug']];
            $product = Product::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'category_id'   => $catId,
                    'name'          => $data['name'],
                    'name_ar'       => $data['name_ar'],
                    'tagline'       => $data['tagline'],
                    'tagline_ar'    => $data['tagline_ar'],
                    'description'   => $data['description'],
                    'description_ar'=> $data['description_ar'],
                    'material'      => $data['material'],
                    'material_ar'   => $data['material_ar'],
                    'origin'        => $data['origin'],
                    'origin_ar'     => $data['origin_ar'],
                    'care'          => $data['care'],
                    'care_ar'       => $data['care_ar'],
                    'shipping'      => $data['shipping'],
                    'shipping_ar'   => $data['shipping_ar'],
                    'price'         => $data['price'],
                    'badge'         => $data['badge'],
                    'is_active'     => true,
                    'is_featured'   => $data['is_featured'],
                    'sort_order'    => $data['sort_order'],
                ]
            );

            // Images
            $product->images()->delete();
            foreach ($data['images'] as $img) {
                $product->images()->create($img);
            }

            // Colors
            $product->colors()->delete();
            foreach ($data['colors'] as $color) {
                $product->colors()->create($color);
            }

            // Details
            $product->details()->delete();
            foreach ($data['details'] as $detail) {
                $product->details()->create($detail);
            }
        }

        $this->command->info('✓ Seeded 12 products with images, colors and details.');
    }
}
